
package View; // dalam sebuah package bernama View 

import Model.Koneksi; // mengimport package model class koneksi untuk mengimport seluruh kodingan di dalamnya
import java.sql.Connection; // Mengimport java.sql.Connection untuk koneksi ke Database
import java.sql.ResultSet; // Mengimport java.sql.ResultSet untuk dapat menampilkan/memilih data di Database 
import java.sql.Statement; // Mengimport java.sql.Statement untuk menggunakan perintah SQL (Insert Update Delete) ke Database
import javax.swing.JOptionPane; // Mengimport javax.swing.JOptionPane untuk menggunakan fitur JOptionPane
import javax.swing.table.DefaultTableModel; // Mengimport javax.swing.table.DefaultTableModel untuk paket class berisi interface dan kelas yang menyediakan tampilan grafis tabel


public class Aplikasi_Kasir extends javax.swing.JFrame { // sebuah public class Aplikasi_Kasir yang meng extend javax.swing.JFrame
    
    String sql; // Mendeklarasikan variable sql dengan tipe data String
    Connection con; // Membuat variable con sebagai perwakilan interface Connection 
    Statement stm; // Membuat variable stm sebagai perwakilan interface Statement 
    ResultSet rs; // Membuat variable rs sebagai perwakilan interface ResultSet
    
    public void clear (){ // Method clear yang digunakan untuk mengosongkan txtHargaBarang,txtJumlahBarang,txtJumlahBayar,txtJumlahHarga,txtKembalian, serta mengembalikan CBNamaBarang menjadi "Pilih Kue"
        txtHargaBarang.setText(""); 
        txtJumlahBarang.setText("");
        txtJumlahBayar.setText("");
        txtJumlahHarga.setText("");
        txtKembalian.setText("");
        CBNamaBarang.setSelectedItem("Pilih Kue");
   }
    
    public void Display_Data(){ // Method Display Data
        Koneksi DB = new Koneksi(); // Membuat objek DB untuk kelas Koneksi
        DB.koneksi(); // Memanggil method koneksi pada kelas Koneksi melalui objek DB
        con=DB.con; // Menyamakan variable con di kelas Aplikasi_Kasir dengan con di kelas Koneksi
        stm=DB.stm; // Menyamakan variable stm di kelas Aplikasi_Kasir dengan stm di kelas Koneksi
        
        DefaultTableModel Model = new DefaultTableModel(); // Membuat objek Model untuk class DefaultTableModel
        Model.addColumn("Nama Barang"); // Menambah kolom "Nama Barang" pada JFrame dan Database
        Model.addColumn("Harga Barang"); // Menambah kolom "Harga Barang" pada JFrame dan Database
        Model.addColumn("Jumlah Barang"); // Menambah kolom "Jumlah Barang" pada JFrame dan Database
        Model.addColumn("Total Harga"); // Menambah kolom "Total Harga" pada JFrame dan Database
        Model.addColumn("Jumlah Bayar"); // Menambah kolom "Jumlah Bayar" pada JFrame dan Database
        
        try { // Statement try
            sql = "SELECT * FROM tbtransaksi"; // Perintah menampilkan data pada Database tbtransaksi
            rs = stm.executeQuery(sql); // Mendefinisikan untuk mendapatkan data dari hasil Query 
            
            while (rs.next()){ // Kondisi while untuk melakukan perulangan terhadap data yang sudah didapatkan dari hasil Query
                Model.addRow(new Object[]{rs.getString(1), rs.getString(2),  
                    rs.getString(3), rs.getString(4),rs.getString(5)}); // Menambahkan baris data pada table 
            }
            TabelTransaksi.setModel(Model); // Menyiapkan instansi TabelTransaksi
        } catch (Exception e) { // statement catch untuk menangkap error Exception
            JOptionPane.showMessageDialog(this, e.getMessage()); // Menampilkan GUI message 
        }
    }
    
    public Aplikasi_Kasir() { // Method Aplikasi_Kasir
        initComponents(); // Menginisialisasi Components
        Display_Data(); // Memanggil method Display_Data
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHargaBarang = new javax.swing.JTextField();
        CBNamaBarang = new javax.swing.JComboBox<>();
        txtJumlahBarang = new javax.swing.JTextField();
        txtJumlahHarga = new javax.swing.JTextField();
        txtJumlahBayar = new javax.swing.JTextField();
        txtKembalian = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnHitungJumlah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelTransaksi = new javax.swing.JTable();
        btnHitungKembalian = new javax.swing.JButton();
        btnSurvey = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHargaBarang.setEditable(false);
        txtHargaBarang.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(txtHargaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 430, 20));

        CBNamaBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kue", "Cheese Cake", "Chocolate Cake", "Black Forest", "Muffin Cake" }));
        CBNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBNamaBarangActionPerformed(evt);
            }
        });
        getContentPane().add(CBNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 68, 430, 20));

        txtJumlahBarang.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(txtJumlahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 430, 20));

        txtJumlahHarga.setEditable(false);
        txtJumlahHarga.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(txtJumlahHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 430, 20));

        txtJumlahBayar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(txtJumlahBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 430, 20));

        txtKembalian.setEditable(false);
        txtKembalian.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(txtKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 430, 20));

        btnSimpan.setContentAreaFilled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 60, 20));

        btnBatal.setContentAreaFilled(false);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 60, 20));

        btnKeluar.setContentAreaFilled(false);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 70, 20));

        btnHitungJumlah.setContentAreaFilled(false);
        btnHitungJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungJumlahActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitungJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 90, 20));

        TabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelTransaksi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 720, 90));

        btnHitungKembalian.setContentAreaFilled(false);
        btnHitungKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungKembalianActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitungKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 120, 20));

        btnSurvey.setContentAreaFilled(false);
        btnSurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSurveyActionPerformed(evt);
            }
        });
        getContentPane().add(btnSurvey, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 50, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AplikasiKasir.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        new Login().setVisible(true);  // Ketika user menekan button keluar maka akan diarahkan ke frame login
        dispose(); // method dispose untuk menutup frame Aplikasi_Kasir
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        clear(); // memanggil method clear
    }//GEN-LAST:event_btnBatalActionPerformed

    private void CBNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBNamaBarangActionPerformed
    String Nama_Barang=(String)CBNamaBarang.getSelectedItem(); // Membuat variable Nama_Barang
    switch (Nama_Barang){ // Swicth Nama_Barang
        case "Cheese Cake": // Case "Cheese Cake"
        txtHargaBarang.setText("150000"); // Harga nya di set "150000"
        break; // syntax break
        case "Chocolate Cake": // Case "Chocolate Cake"
        txtHargaBarang.setText("130000"); // Harga nya di set "130000"
        break; // syntax break
        case "Black Forest": // Case "Black Forest"
        txtHargaBarang.setText("200000"); // Harga nya di set "200000"
        break; // syntax break
        case "Muffin Cake": // Case "Muffin Cake"
        txtHargaBarang.setText("75000"); // Harga nya di set "75000"
        break; // syntax break
    }
    }//GEN-LAST:event_CBNamaBarangActionPerformed

    private void btnHitungJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungJumlahActionPerformed
        int Jumlah_Barang=Integer.parseInt(txtJumlahBarang.getText()); // Mengkonversi txtJumlahBarang menjadi integer dan ditampung dalam variable Jumlah_Barang 
        int Harga_barang=Integer.parseInt(txtHargaBarang.getText()); // Mengkonversi txtHargaBarang menjadi integer dan ditampung dalam variable Harga_barang
        txtJumlahHarga.setText(Integer.toString(Jumlah_Barang*Harga_barang)); // Meng set txtJumlahHarga dengan parameter (Jumlah_Barang*Harga_barang) serta mengkonversi nya menjadi string agar dapat ditampilkan dalam frame
    }//GEN-LAST:event_btnHitungJumlahActionPerformed

    private void btnHitungKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungKembalianActionPerformed
        int Jumlah_Harga =Integer.parseInt(txtJumlahHarga.getText()); // Mengkonversi txtJumlahHarga menjadi integer dan ditampung dalam variable Jumlah_Harga
        int Jumlah_Bayar =Integer.parseInt(txtJumlahBayar.getText()); // Mengkonversi txtJumlahBayar menjadi integer dan ditampung dalam variable Jumlah_Bayar
        if(Jumlah_Bayar >= Jumlah_Harga){ // Kondisi if Jumlah_Bayar lebih besar sama dengan Jumlah_Harga
            txtKembalian.setText(Integer.toString(Jumlah_Bayar-Jumlah_Harga)); // maka txtKembalian yang dikonversi menjadi string mempunyai parameter (Jumlah_Bayar-Jumlah_Harga) 
        }else { // kondisi else atau lainnya
            JOptionPane.showMessageDialog(null, "Uang Anda Tidak Cukup"); // Memunculkan GUI Message dengan pesan "Uang Anda Tidak Cukup)
        }
    }//GEN-LAST:event_btnHitungKembalianActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        Koneksi DB = new Koneksi(); // Membuat objek DB untuk kelas Koneksi
        DB.koneksi(); // Memanggil method koneksi pada kelas Koneksi melalui objek DB
        con=DB.con; // Menyamakan variable con di kelas Aplikasi_Kasir dengan con di kelas Koneksi
        stm=DB.stm; // Menyamakan variable stm di kelas Aplikasi_Kasir dengan stm di kelas Koneksi
        
        try { // Statement try
            sql = "INSERT INTO tbtransaksi VALUES ('"+CBNamaBarang.getSelectedItem()+"','"+txtHargaBarang.getText()+"','"
                    +txtJumlahBarang.getText()+"','"+txtJumlahHarga.getText()+"','"+txtJumlahBayar.getText()+"')"; // Perintah untuk menampilkan data pada Database tbtransaksi
            stm.execute(sql); // Mengexecute  hasil Query
            JOptionPane.showMessageDialog(null, "Proses Simpan Berhasil"); // Menampilkan GUI message "Proses Simpan Berhasil
            Display_Data(); // Memanggil method Display_Data
            clear(); // Memanggil method Clear
        } catch (Exception e) { // Statement catch untuk menangkap error Exception
            JOptionPane.showMessageDialog(this, e.getMessage()); // Menampilkan GUI message
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnSurveyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurveyActionPerformed
        new SurveyCustomer().setVisible(true); // Ketika user menekan button Survey maka akan diarahkan ke frame SurveyCustomer
        dispose(); // method dispose untuk menutup frame Aplikasi_Kasir
    }//GEN-LAST:event_btnSurveyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBNamaBarang;
    private javax.swing.JTable TabelTransaksi;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHitungJumlah;
    private javax.swing.JButton btnHitungKembalian;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSurvey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHargaBarang;
    private javax.swing.JTextField txtJumlahBarang;
    private javax.swing.JTextField txtJumlahBayar;
    private javax.swing.JTextField txtJumlahHarga;
    private javax.swing.JTextField txtKembalian;
    // End of variables declaration//GEN-END:variables
}
