
package View; // Dalam sebuah package dengan nama View

import Model.Koneksi; // mengimport package model class koneksi untuk mengimport seluruh kodingan di dalamnya
import java.sql.Connection; // Mengimport java.sql.Connection untuk koneksi ke Database
import java.sql.ResultSet; // Mengimport java.sql.ResultSet untuk dapat menampilkan/memilih data di Database 
import java.sql.Statement; // Mengimport java.sql.Statement untuk menggunakan perintah SQL (Insert Update Delete) ke Database
import javax.swing.JOptionPane; // Mengimport javax.swing.JOptionPane untuk menggunakan fitur JOptionPane

public class Login extends javax.swing.JFrame { // Sebuah public class login yang meng extend javax.swing.JFrame
    
    String Username, Password, sql; // Mendeklarasikan variable Username, Password, dan sql
    Connection con; // Membuat variable con sebagai perwakilan objek Connection 
    Statement stm; // Membuat variable  stm sebagai perwakilan objek Statement 
    ResultSet rs; // Membuat variable rs sebagai perwakilan objek ResultSet
    
    public Login() { // Method Login 
        initComponents(); // Menginisialisasi Components
        Koneksi DB = new Koneksi(); // Membuat objek DB untuk kelas Koneksi
        DB.koneksi(); // Memanggil method koneksi pada kelas Koneksi melalui objek DB
        con=DB.con; // Menyamakan variable con di kelas Aplikasi_Kasir dengan con di kelas Koneksi
        stm=DB.stm; // Menyamakan variable stm di kelas Aplikasi_Kasir dengan stm di kelas Koneksi
    }

     public void clean(){ // method clean yang digunakan untuk mengosongkan txtPassword dan txtUsername
        txtPassword.setText(""); 
        txtUsername.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 180, 30));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 212, 180, 30));

        btnLogin.setContentAreaFilled(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 80, 30));

        btnSignUp.setContentAreaFilled(false);
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 160, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resizelogin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try { // Statement try
           sql = "SELECT * FROM tblogin WHERE username='"+txtUsername.getText()+"' AND password='"+txtPassword.getText()+"'"; // Perintah untuk menampilkan data pada Database tblogin 
            rs = stm.executeQuery(sql); // Mendefinisikan untuk mendapatkan data dari hasil Query
            if(rs.next()){ // Kondisi if next
                if(txtUsername.getText().equals(rs.getString("username")) && txtPassword.getText().equals(rs.getString("password"))){ // kondisi if txtUsername equals string username dan txtPassword equals string password
                    JOptionPane.showMessageDialog(null, "Berhasil Login"); // Menampilkan GUI Message "Berhasil Login"
                    new Aplikasi_Kasir().setVisible(true); // Ketika user menekan Login button maka akan diarahkan ke frame Aplikasi_Kasir 
                    this.setVisible(false); 
                }
            }
            
            sql = "SELECT * FROM tbsignup WHERE username='"+txtUsername.getText()+"' AND password='"+txtPassword.getText()+"'"; // Perintah untuk menampilkan data pada Database tbsignup
            rs = stm.executeQuery(sql); // Mendefinisikan untuk mendapatkan data dari hasil Query
            if(rs.next()){ // Kondisi if next
                if(txtUsername.getText().equals(rs.getString("username")) && txtPassword.getText().equals(rs.getString("password"))){ // kondisi if txtUsername equals string username dan txtPassword equals string password
                    JOptionPane.showMessageDialog(null, "Berhasil Login"); // Menampilkan GUI Message "Berhasil Login"
                    new Aplikasi_Kasir().setVisible(true); // Ketika user menekan Login button maka akan diarahkan ke frame Aplikasi_Kasir 
                     this.setVisible(false);
                }
            } 
        } catch (Exception e) { // Statement catch untuk menangkap error Exception
            JOptionPane.showMessageDialog(this, e.getMessage()); // Menampilkan GUI Message
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        new SignUp().setVisible(true); // Ketika user menekan SignUp maka akan diarahkan ke frame SignUp
        dispose(); // Method dispose untuk menutup frame Login
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
