
package View; // Dalam sebuah package dengan nama View

import Model.Koneksi; // mengimport package model class koneksi untuk mengimport seluruh kodingan di dalamnya
import java.sql.Connection; // Mengimport java.sql.Connection untuk koneksi ke Database
import java.sql.ResultSet; // Mengimport java.sql.ResultSet untuk dapat menampilkan/memilih data di Database 
import java.sql.Statement; // Mengimport java.sql.Statement untuk menggunakan perintah SQL (Insert Update Delete) ke Database
import javax.swing.JOptionPane; // Mengimport javax.swing.JOptionPane untuk menggunakan fitur JOptionPane

public class SignUp extends javax.swing.JFrame { // Sebuah public class SignUp yang meng extend javax.swing.JFrame

    String user, Password, RePassword, Fullname; // Mendeklarasikan variable user, Password, RePassword, Fullname bertipe data string
    int P_User=50; // Mendeklarasikan variable P_User bertipe data integer dengan inisialisasi 50
    Connection con; // Membuat variable con sebagai perwakilan objek Connection 
    Statement stm; // Membuat variable  stm sebagai perwakilan objek Statement 
    ResultSet rs; // Membuat variable rs sebagai perwakilan objek ResultSet    
    
    public SignUp() { // Method SignUp
        initComponents(); // Menginisialisasi Components
        Koneksi DB = new Koneksi(); // Membuat objek DB untuk kelas Koneksi
        DB.koneksi(); // Memanggil method koneksi pada kelas Koneksi melalui objek DB
        con=DB.con; // Menyamakan variable con di kelas Aplikasi_Kasir dengan con di kelas Koneksi
        stm=DB.stm; // Menyamakan variable stm di kelas Aplikasi_Kasir dengan stm di kelas Koneksi
    }
    
    public void clean(){ // Method clean yang digunakan untuk megosongkan txtFullname, txtPassword, txtRePassword, txtUsername
        txtFullname.setText("");
        txtPassword.setText("");
        txtRePassword.setText("");
        txtUsername.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFullname = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFullname.setPreferredSize(new java.awt.Dimension(57, 20));
        getContentPane().add(txtFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 102, 280, 30));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 154, 280, 30));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 207, 280, 30));

        txtRePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 280, 30));

        btnSignUp.setContentAreaFilled(false);
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 80, 30));

        btnLogin.setContentAreaFilled(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 160, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Signup.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        Fullname = txtFullname.getText(); // Menginisialisasi variable Fullname dengan txtFullname.getText()
        Password = txtPassword.getText(); // Menginisialisasi variable Password dengan txtPassword.getText()
        RePassword = txtRePassword.getText(); // Menginisialisasi variable RePassword dengan txtRePassword.getText()
        P_User = txtUsername.getText().length(); // Menginisialisasi variable P_User dengan txtUsername.getText().length()
        
        try { // Statement try
            if (RePassword.equals(Password) && P_User>=2) { // kondisi if RePassword equals Password dan P_User lebih dari sama dengan 2
                stm.executeUpdate("insert into tbsignup values ("
                        + "'" + txtFullname.getText() + "',"
                        + "'" + txtUsername.getText() + "',"
                        + "'" + String.valueOf(txtPassword.getPassword()) + "',"
                        + "'" + String.valueOf(txtRePassword.getPassword()) + "')" // Melakukan update pada Database tbsignup
                );
                {
                    JOptionPane.showMessageDialog(null, "Save Succesfull"); // Menampilkan GUI Message "Save Succesfull"
                    new Login().setVisible(true); // Ketika user menekan button Login maka akan diarahkan ke frame Login
                    this.setVisible(false);
                }
                clean(); // Memanggil method clean()
            } else { // kondisi else atau lainnya
                JOptionPane.showMessageDialog(null, "Access Denied"); // Menampilkan GUI Message "Access Denied"
                clean(); // Memanggil method clean()
            };
        } catch (Exception e) { // Statement catch untuk menangkap error exception
            JOptionPane.showMessageDialog(this, e.getMessage()); // Menampilkan GUI Message
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void txtRePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRePasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        new Login().setVisible(true); // Ketika user menekan button Login maka akan diarahkan ke frame Login
        dispose(); // Method dispose untuk menutup frame SignUp
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
