package View; // Dalam sebuah package bernama View

import Model.Koneksi; // mengimport package model class koneksi untuk mengimport seluruh kodingan di dalamnya
import java.sql.Connection; // Mengimport java.sql.Connection untuk koneksi ke Database
import java.sql.ResultSet; // Mengimport java.sql.ResultSet untuk dapat menampilkan/memilih data di Database 
import java.sql.Statement; // Mengimport java.sql.Statement untuk menggunakan perintah SQL (Insert Update Delete) ke Database
import javax.swing.JOptionPane; // Mengimport javax.swing.JOptionPane untuk menggunakan fitur JOptionPane
import javax.swing.table.DefaultTableModel; // Mengimport javax.swing.table.DefaultTableModel untuk paket class berisi interface dan kelas yang menyediakan tampilan grafis tabel

public class SurveyCustomer extends javax.swing.JFrame { // Sebuah public class SurveyCustomer yang meng extend javax.swing.JFrame
    
    String sql; // Mendeklarasikan variable sql dengan tipe data String
    Connection con; // Membuat variable con sebagai perwakilan interface Connection 
    Statement stm; // Membuat variable stm sebagai perwakilan interface Statement 
    ResultSet rs; // Membuat variable rs sebagai perwakilan interface ResultSet
    
    public void clear (){ // Method clear untuk mengosongkan field
        txtRasa.setText("");
        txtCustomer.setText("");
        txtHarga.setText("");
        txtBentuk.setText("");
        cbKue.setSelectedItem("Pilih Kue");
        txtButtonGroup1.clearSelection();
        txtButtonGroup2.clearSelection();
        txtButtonGroup3.clearSelection();
   }
    
    public void Display_Data(){
        Koneksi DB = new Koneksi();
        DB.koneksi();
        con=DB.con;
        stm=DB.stm;
        
        DefaultTableModel Model = new DefaultTableModel(); // Membuat objek Model untuk class DefaultTableModel
        Model.addColumn("Nama Customer"); // Menambah kolom "Nama Costumer" pada JFrame dan Database
        Model.addColumn("Produk"); // Menambah kolom "Produk" pada JFrame dan Database
        Model.addColumn("Rasa Kue"); // Menambah kolom "Rasa Kue" pada JFrame dan Database
        Model.addColumn("Bentuk Kue"); // Menambah kolom "Bentuk Kue" pada JFrame dan Database
        Model.addColumn("Harga Kue"); // Menambah kolom "Harga Kue" pada JFrame dan Database
        
        try { // Statement try
            sql = "SELECT * FROM tbsurvey"; // Perintah menampilkan data pada Database tbsurvey
            rs = stm.executeQuery(sql); // Mendefinisikan untuk mendapatkan data dari hasil query
            
            while (rs.next()){ // Kondisi while untuk melakukan perulangan terhadap data yang sudah didapatkan dari hasil Query
                Model.addRow(new Object[]{rs.getString(1), rs.getString(2), 
                    rs.getString(3), rs.getString(4),rs.getString(5)}); // Menambahkan baris data pada table
            }
            TabelSurvey.setModel(Model); // Menyiapkan instansi TabelSurvey
        } catch (Exception e) { // Statement catch untuk menangkap error exception
            JOptionPane.showMessageDialog(this, e.getMessage()); // Menampilkan GUI Message
        }
    }
    
    public SurveyCustomer() { // Method SurveyCustomer
        initComponents(); // Menginisialisasi Components
        Display_Data(); // Memanggil method Display_Data
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtButtonGroup1 = new javax.swing.ButtonGroup();
        txtButtonGroup2 = new javax.swing.ButtonGroup();
        txtButtonGroup3 = new javax.swing.ButtonGroup();
        txtCustomer = new javax.swing.JTextField();
        cbKue = new javax.swing.JComboBox<>();
        txtRasa = new javax.swing.JTextField();
        rbRasaSB = new javax.swing.JRadioButton();
        rbRasaB = new javax.swing.JRadioButton();
        rbRasaE = new javax.swing.JRadioButton();
        rbRasaSE = new javax.swing.JRadioButton();
        txtBentuk = new javax.swing.JTextField();
        rbBentukSB = new javax.swing.JRadioButton();
        rbBentukB = new javax.swing.JRadioButton();
        rbBentukM = new javax.swing.JRadioButton();
        rbBentukSM = new javax.swing.JRadioButton();
        txtHarga = new javax.swing.JTextField();
        rbHargaSM = new javax.swing.JRadioButton();
        rbHargaM = new javax.swing.JRadioButton();
        rbHargaN = new javax.swing.JRadioButton();
        rbHargaMH = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelSurvey = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(txtCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 66, 390, 24));

        cbKue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kue", "Cheese Cake", "Chocolate Cake", "Black Forest", "Muffin Cake" }));
        cbKue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKueActionPerformed(evt);
            }
        });
        getContentPane().add(cbKue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 95, 390, -1));

        txtRasa.setEditable(false);
        getContentPane().add(txtRasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 470, 30));

        txtButtonGroup1.add(rbRasaSB);
        rbRasaSB.setText("Sangat Buruk");
        rbRasaSB.setContentAreaFilled(false);
        getContentPane().add(rbRasaSB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        txtButtonGroup1.add(rbRasaB);
        rbRasaB.setText("Buruk");
        rbRasaB.setContentAreaFilled(false);
        getContentPane().add(rbRasaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, 30));

        txtButtonGroup1.add(rbRasaE);
        rbRasaE.setText("Enak");
        rbRasaE.setContentAreaFilled(false);
        getContentPane().add(rbRasaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        txtButtonGroup1.add(rbRasaSE);
        rbRasaSE.setText("Sangat Enak");
        rbRasaSE.setContentAreaFilled(false);
        getContentPane().add(rbRasaSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        txtBentuk.setEditable(false);
        getContentPane().add(txtBentuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 470, 30));

        txtButtonGroup2.add(rbBentukSB);
        rbBentukSB.setText("Sangat Buruk");
        rbBentukSB.setContentAreaFilled(false);
        getContentPane().add(rbBentukSB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 20));

        txtButtonGroup2.add(rbBentukB);
        rbBentukB.setText("Buruk");
        rbBentukB.setContentAreaFilled(false);
        rbBentukB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBentukBActionPerformed(evt);
            }
        });
        getContentPane().add(rbBentukB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        txtButtonGroup2.add(rbBentukM);
        rbBentukM.setText("Menarik");
        rbBentukM.setContentAreaFilled(false);
        rbBentukM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBentukMActionPerformed(evt);
            }
        });
        getContentPane().add(rbBentukM, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        txtButtonGroup2.add(rbBentukSM);
        rbBentukSM.setText("Sangat Menarik");
        rbBentukSM.setContentAreaFilled(false);
        getContentPane().add(rbBentukSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        txtHarga.setEditable(false);
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 470, 30));

        txtButtonGroup3.add(rbHargaSM);
        rbHargaSM.setText("Sangat Murah");
        rbHargaSM.setContentAreaFilled(false);
        getContentPane().add(rbHargaSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 100, 20));

        txtButtonGroup3.add(rbHargaM);
        rbHargaM.setText("Murah");
        rbHargaM.setContentAreaFilled(false);
        getContentPane().add(rbHargaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        txtButtonGroup3.add(rbHargaN);
        rbHargaN.setText("Normal");
        rbHargaN.setContentAreaFilled(false);
        getContentPane().add(rbHargaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        txtButtonGroup3.add(rbHargaMH);
        rbHargaMH.setText("Mahal");
        rbHargaMH.setContentAreaFilled(false);
        getContentPane().add(rbHargaMH, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        TabelSurvey.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelSurvey);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 650, 100));

        btnSave.setContentAreaFilled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 40, 20));

        btnBatal.setContentAreaFilled(false);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 40, 20));

        btnKeluar.setContentAreaFilled(false);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 40, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Survey.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbBentukBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBentukBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBentukBActionPerformed

    private void txtCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerActionPerformed

    private void cbKueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKueActionPerformed
        String Nama_Kue=(String)cbKue.getSelectedItem(); // Membuat variable Nama_Kue
        switch (Nama_Kue){ // Switch Nama_Kue
        case "Cheese Cake": // Case "Cheese Cake"
        txtRasa.setText("Bagaimana rasa cheese cakenya?"); // setText menampilkan pertanyaan
        txtBentuk.setText("Bagaimana bentuk cheese cakenya?"); // setText menampilkan pertanyaan 
        txtHarga.setText("Bagaimana harga cheese cakenya?"); // setText menampilkan pertanyaan  
        break; // syntax break
        case "Chocolate Cake": // case "Chocolate Cake"
        txtRasa.setText("Bagaimana rasa chocolate cakenya?"); // setText menampilkan pertanyaan
        txtBentuk.setText("Bagaimana bentuk chocolate cakenya?"); // setText menampilkan pertanyaan
        txtHarga.setText("Bagaimana harga chocolate cakenya?"); // setText menampilkan pertanyaan
        break; // syntax break
        case "Black Forest": // case "Black Forest"
        txtRasa.setText("Bagaimana rasa black forest cakenya?"); // setText menampilkan pertanyaan
        txtBentuk.setText("Bagaimana bentuk black forest cakenya?"); // setText menampilkan pertanyaan
        txtHarga.setText("Bagaimana harga black forest cakenya?"); // setText menampilkan pertanyaan
        break; // syntax break
        case "Muffin Cake": // case "Muffin Cake" 
        txtRasa.setText("Bagaimana rasa muffin cakenya?"); // setText menampilkan pertanyaan
        txtBentuk.setText("Bagaimana bentuk muffin cakenya?"); // setText menampilkan pertanyaan
        txtHarga.setText("Bagaimana harga muffin cakenya?"); // setText menampilkan pertanyaan
        break; // syntax break
    }
    }//GEN-LAST:event_cbKueActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String rasa = null, bentuk = null , harga = null; // deklarasi variable rasa,bentuk,harga bertipe data String dengan inisialisasi null
        if (rbRasaSB.isSelected()){ // kondisi jika rbRasaSB terpilih
            rasa = "Sangat Buruk"; // variable rasa dengan inisialisasi "Sangat Buruk"
        }else if (rbRasaB.isSelected()){ // kondisi lainnya jika rbRasaB terpilih 
            rasa = "Buruk"; // variable rasa dengan inisialisasi "Buruk"
        }else if (rbRasaE.isSelected()){ // kondisi lainnya jika rbRasaE terpilih
            rasa = "Enak"; // variable rasa dengan inisialisasi "Enak"
        }else if (rbRasaSE.isSelected()){ // kondisi lainnya jika rbRasaSE  terpilih
            rasa = "Sangat Enak"; // variable rasa dengan inisialisasi "Sangat Enak"
        }else { // kondisi lainnya 
            rasa = "-"; // variable rasa dengan inisialisasi "-"
        }
        
        if (rbBentukSB.isSelected()){ // kondisi jika rbBentukSB terpilih
            bentuk = "Sangat Buruk"; // variable bentuk dengan inisialisasi "Sangat Buruk"
        }else if (rbBentukB.isSelected()){ // kondisi lainnya jika rbBentukB
            bentuk = "Buruk"; // variable bentuk dengan inisialisasi "Buruk"
        }else if (rbBentukM.isSelected()){ // kondisi lainnya jika rbBentukM
            bentuk = "Menarik"; // variable bentuk dengan inisialisasi "Menarik"
        }else if (rbBentukSM.isSelected()){ // kondisi lainnya jika rbBentukSM 
            bentuk = "Sangat Menarik"; // variable bentuk dengan inisialisasi "Sangat Menarik"
        }else{ // kondisi lainnya 
            bentuk = "-"; // variable bentuk dengan inisialisasi "-"
        }
        
        if (rbHargaSM.isSelected()){ // kondisi jika rbHargaSM terpilih
            harga = "Sangat Murah"; // variable harga dengan inisialisasi "Sangat Murah"
        }else if (rbHargaM.isSelected()){ // kondisi lainnya jika rbHargaM terpilih
            harga = "Murah"; // variable harga dengan inisialisasi "Murah"
        }else if (rbHargaN.isSelected()){ // kondisi lainnya jika rbHargaN terpilih
            harga = "Normal"; // variable harga dengan insialisasi "Normal"
        }else if (rbHargaMH.isSelected()){ // kondisi lainnya jika rbHargaMH terpilih
            harga = "Mahal"; // variable harga dengan inisialisasi "Mahal"
        }else { // kondisi lainnya
            harga = "-"; // variable harga dengan inisialisasi "-"
        }
        
        Koneksi DB = new Koneksi(); // Membuat objek DB untuk kelas Koneksi
        DB.koneksi(); // Memanggil method koneksi pada kelas Koneksi melalui objek DB
        con=DB.con; // Menyamakan variable con di kelas Aplikasi_Kasir dengan con di kelas Koneksi
        stm=DB.stm; // Menyamakan variable stm di kelas Aplikasi_Kasir dengan stm di kelas Koneksi
        
        try { // statement try
            sql = "INSERT INTO tbsurvey VALUES ('"+txtCustomer.getText()+"','"+cbKue.getSelectedItem()+"','"
                    +rasa+"','"+bentuk+"','"+harga+"')"; // perintah untuk menampilkan data pada Database  tbsurvey
            stm.execute(sql); // Mendefinisikan untuk mendapatkan data dari hasil query
            JOptionPane.showMessageDialog(null, "Proses Simpan Berhasil"); // Menampilkan GUI Message "Proses Simpan Berhasil"
            Display_Data(); // Memanggil method Display_Data()
            clear(); // Memanggil method clear()
        } catch (Exception e) { // statement catch untuk menangkap error Exception 
            JOptionPane.showMessageDialog(this, e.getMessage()); // Menampilkan GUI Message
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        clear(); // Memanggil method clear()
    }//GEN-LAST:event_btnBatalActionPerformed

    private void rbBentukMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBentukMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBentukMActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0); // System Exit yang membuat Sistem akan keluar dari JFrame ketika user menekan button Keluar
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SurveyCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SurveyCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SurveyCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SurveyCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SurveyCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelSurvey;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbKue;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbBentukB;
    private javax.swing.JRadioButton rbBentukM;
    private javax.swing.JRadioButton rbBentukSB;
    private javax.swing.JRadioButton rbBentukSM;
    private javax.swing.JRadioButton rbHargaM;
    private javax.swing.JRadioButton rbHargaMH;
    private javax.swing.JRadioButton rbHargaN;
    private javax.swing.JRadioButton rbHargaSM;
    private javax.swing.JRadioButton rbRasaB;
    private javax.swing.JRadioButton rbRasaE;
    private javax.swing.JRadioButton rbRasaSB;
    private javax.swing.JRadioButton rbRasaSE;
    private javax.swing.JTextField txtBentuk;
    private javax.swing.ButtonGroup txtButtonGroup1;
    private javax.swing.ButtonGroup txtButtonGroup2;
    private javax.swing.ButtonGroup txtButtonGroup3;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtRasa;
    // End of variables declaration//GEN-END:variables
}
